config:
  explorerTitle: "Incomes Across the Distribution - Luxembourg Income Study"
  explorerSubtitle: "Explore Luxembourg Income Study data on the distribution of incomes."
  selection:
    - Brazil
    - Chile
    - China
    - France
    - South Africa
    - United States
  wpBlockId: 57755
  isPublished: true
  # pickerColumnSlugs:

dimensions:
  - name: Indicator
    slug: indicator
    choices:
      - slug: mean
        name: Mean income
      - slug: median
        name: Median income
      - slug: avg
        name: Mean income, by decile
      - slug: thr
        name: Decile thresholds
      - slug: share
        name: Decile shares
  - name: Decile
    slug: decile
    choices:
      - slug: "1"
        name: "1 (poorest)"
      - slug: "2"
        name: "2"
      - slug: "3"
        name: "3"
      - slug: "4"
        name: "4"
      - slug: "5"
        name: "5"
      - slug: "6"
        name: "6"
      - slug: "7"
        name: "7"
      - slug: "8"
        name: "8"
      - slug: "9"
        name: "9"
      - slug: "10"
        name: "10"
      - slug: all
        name: All deciles
  - name: Income measure
    slug: welfare_type
    choices:
      - slug: "dhi"
        name: "After tax"
      - slug: "mi"
        name: "Before tax"
      - slug: "after_vs_before_tax"
        name: "After vs. before tax"
  - name: Adjust for cost sharing within households (equivalized income)
    slug: equivalence_scale
    choices:
      - slug: "per capita"
        name: "Per capita"
      - slug: "square root"
        name: "Equivalized"

views: []
