steps:
  # NASA Ozone Watch
  data://meadow/nasa/2023-03-06/ozone_hole_area:
    - snapshot://nasa/2023-03-06/ozone_hole_area_p2.txt
    - snapshot://nasa/2023-03-06/ozone_hole_area_p1.txt
  data://garden/nasa/2023-03-06/ozone_hole_area:
    - data://meadow/nasa/2023-03-06/ozone_hole_area
  data://grapher/nasa/2023-03-06/ozone_hole_area:
    - data://garden/nasa/2023-03-06/ozone_hole_area
