title:
  title: Gini coefficient
  title_variant: World Bank
topic_tags:
  - Economic Inequality

default_selection:
  - Chile
  - Brazil
  - South Africa
  - China
  - Nigeria
  - United States

default_dimensions:
  survey_comparability: No spells

originUrl: ourworldindata.org/economic-inequality

dimensions:
  - name: Breaks in data
    slug: survey_comparability
    description: The data provider reports where trends in countries are affected by changes in methodology. These breaks can be shown in the chart.
    choices:
      - slug: No spells
        name: Don't show
        description: Better for making broad comparisons across several countries
      - slug: Spells
        name: Show
        description: Better for understanding trends within individual countries

views: []
