title:
  title: Incomes across the distribution
  title_variant: World Bank
default_selection:
  - World
  - United States
  - South Korea
  - Spain
  - China
  - Mauritania
  - Ghana
  - India
  - Ethiopia
  - Democratic Republic of Congo

dimensions:
  - name: Metric
    slug: indicator
    choices:
      - slug: mean
        name: Mean income or consumption
        # description: The share of the population living below the selected poverty line
      - slug: median
        name: Median income or consumption
        # description: The number of people living below the selected poverty line
      - slug: avg
        name: Mean income or consumption, by decile
        # description:
      - slug: thr
        name: Decile thresholds
        # description:
      - slug: share
        name: Decile shares
        # description:

  - name: Decile
    slug: decile
    choices:
      - slug: "1"
        name: "1 (poorest)"
      - slug: "2"
        name: "2"
      - slug: "3"
        name: "3"
      - slug: "4"
        name: "4"
      - slug: "5"
        name: "5"
      - slug: "6"
        name: "6"
      - slug: "7"
        name: "7"
      - slug: "8"
        name: "8"
      - slug: "9"
        name: "9"
      - slug: "10"
        name: "10 (richest)"
      - slug: all
        name: All deciles
      - slug: nan
        name: ""

  - name: Period
    slug: period
    choices:
      - slug: "day"
        name: "Day"
      - slug: "month"
        name: "Month"
      - slug: "year"
        name: "Year"
      - slug: "nan"
        name: ""

  - name: Breaks in data
    slug: survey_comparability
    description: The data provider reports where trends in countries are affected by changes in methodology. These breaks can be shown in the chart.
    choices:
      - slug: No spells
        name: Don't show
        description: Better for making broad comparisons across several countries
      - slug: Spells
        name: Show
        description: Better for understanding trends within individual countries
views: []
