title:
  title: Religious composition
  title_variant: ""
default_selection:
  - India
  - Indonesia
  - United Kingdom
  - Egypt
  - World
  - United States
  - China
definitions:
  common_views:
    - config:
        chartTypes: ["SlopeChart", "DiscreteBar"]
        hasMapTab: true
        originUrl: ourworldindata.org/war-and-peace

dimensions:
  - slug: religion
    name: Religion
    choices:
      - slug: "religion_distrib"
        name: "Religious composition"
        group: "Aggregates"
        description: Distribution of population by religion
      - slug: "any_religion"
        name: "Any religion"
        group: "Aggregates"
        description: People affiliated to any religion
      - slug: "christians"
        name: "Christianity"
        group: "Major religions"
      - slug: "muslims"
        name: "Islam"
        group: "Major religions"
      - slug: "hindus"
        name: "Hinduism"
        group: "Major religions"
      - slug: "buddhists"
        name: "Buddhism"
        group: "Major religions"
      - slug: "jews"
        name: "Judaism"
        group: "Major religions"
      - slug: "other_religions"
        name: "Other religions"
        group: "Major religions"
      - slug: "religiously_unaffiliated"
        name: "No religion"
        group: "Major religions"

  - slug: indicator
    name: Measure
    choices:
      - slug: "share"
        name: "Share of population"
        description: People affiliated to a religion as a percentage of the total population
      - slug: "count_unrounded"
        name: "Number of people"
        description: Number of deaths divided by the total population
views: []
