title:
  title: Population of cities, towns, and rural areas
  title_variant: by settlement type

default_selection:
  - World
  - China
  - India
  - United States
  - Indonesia

topic_tags:
  - Urbanization

dimensions:
  - slug: "location_type"
    name: "Settlement type"
    choices:
      - slug: "urban_centre"
        name: "Cities"
        description: "Settlements with at least 1,500 people per square kilometre and at least 50,000 people in total."
      - slug: "urban_cluster"
        name: "Towns and suburbs"
        description: "Settlements with at least 300 people per square kilometre and at least 5,000 people in total."
      - slug: "rural_total"
        name: "Rural areas"
        description: "Settlements with fewer than 300 people per square kilometre, or denser areas that are not part of a city or town."
      - slug: "urban_total"
        name: "Urban areas (cities and towns)"
        description: "Population in cities and towns combined."
      - slug: "location_type_stacked"
        name: "All (stacked)"
        description: "Cities, towns, and rural areas shown in a stacked area chart"
      - slug: "by_dominant_type"
        name: "Dominant settlement type"
        description: "Shows whether cities, towns, or rural areas contain the largest share of the population."

  - slug: "metric"
    name: "Metric"
    choices:
      - slug: "population"
        name: "Number of people"
        description: "Total population in absolute numbers"
      - slug: "popshare"
        name: "Share of population (%)"
        description: "Share of total population as a percentage"
      - slug: "density"
        name: "Population density (people per sq km)"
        description: "Population density in people per square kilometre"
      - slug: "popshare_change"
        name: "Change in population share (pp)"
        description: "Change in population share in percentage points over 5-year intervals."
      - slug: "dominant_type"
        name: "Dominant settlement type"
        description: "Shows whether cities, towns, or rural areas contain the largest share of the population."

  - slug: "data_type"
    name: "Data type"
    choices:
      - slug: "estimates"
        name: "Estimates"
        description: "Historical estimates (before 2025)"
      - slug: "projections"
        name: "Projections"
        description: "Future projections (2025 onwards)"

views:
  # Views will be filled out programmatically.
  []
